### PR TITLE
🥛 Add sane defaults for width, height, direction

### LINKED ISSUE #1: Feedback
Hey! 👋 Great little lib, I'm playing around with it and react-three-fiber, since laying stuff out is usually painful: https://codesandbox.io/s/blissful-lake-84hxp (<= this might explode while I work on it :D )

Here's a couple of quick things:

1. `gap` and `margin` properties. In the example I wanted to add some gap between items, it would be great being able to do it without having to add a container
2. `direction` could default to `row` like `flex-direction` does in css
3. `height` and `width` defaults (`auto` probably), just to reduce boilerplate

Anyway, main message is: Kudos, this is great!

### PR DESCRIPTION
**Pull request by caesarsol**
Closes #1 :)

(Please merge after #3, I rebased onto there to make sure tests were still passing)

### CODE REVIEW

**Comment by ivanross** [comment]
@caesarsol I think types should be updated

**Comment by caesarsol** [comment]
@ivanross whicch ones? I don't see type errors, is that what you mean?

**Comment by ivanross** [comment]
width, height, direction, padding, top, and left are now optional

**Comment by caesarsol** [comment]
@ivanross done! Also fixed the defaulting of the children dimensions, I did an error there.

**Review by ivanross — APPROVED** [review]

**Pull request merged**
